# Generated by Django 4.2.4 on 2023-08-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_score_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='scores',
        ),
    ]
