# Generated by Django 4.2.4 on 2023-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_score_score_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
