# Generated by Django 4.2.4 on 2023-08-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
