# Generated by Django 4.2.4 on 2023-08-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_score_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
