# Generated by Django 4.2.4 on 2023-08-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_score_name_score_email_score_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='email',
            new_name='name',
        ),
    ]
