# Generated by Django 4.2.2 on 2023-08-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
