# Generated by Django 4.2.2 on 2023-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
